services:
  postgres:
    image: pgvector/pgvector:0.8.6-pg16
    container_name: spring-ai-postgres
    environment:
      POSTGRES_DB: spring_ai_demo
      POSTGRES_USER: stef
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
