server:
  port: 8585

spring:
  application:
    name: spring_ai_demo

  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.vectorstore.pgvector.PgVectorStoreAutoConfiguration
      - org.springframework.ai.model.chat.client.autoconfigure.ChatClientAutoConfiguration
      - org.springframework.ai.model.ollama.autoconfigure.OllamaEmbeddingAutoConfiguration


  datasource:
    url: jdbc:postgresql://localhost:5432/general_demo
    #url: jdbc:postgresql://localhost:5433/spring_ai_demo
    username: stef
    password: ${DB_PASS}

  ai:
    #vectorstore:
    #  pgvector:
    #    initialize-schema: true
    openai:
      api-key: ${OPEN_API_KEY}
      admin-api-key: ${OPEN_ADMIN_KEY}
      chat:
        model: gpt-5.6-luna
        options:
          reasoning-effort: none
      embedding:
        model: text-embedding-3-small
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.1:8b-instruct-q4_K_M
tavily:
  api-key: ${TAV_KEY}

logging:
  level:
    root: WARN
    com.example.spring_ai_demo.controller: INFO
    com.example.spring_ai_demo.service: INFO
    com.example.spring_ai_demo.tool: DEBUG

  pattern:
    console: "%-5level| %-90msg | %class{15} %d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}%n"